package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

type Config struct {
	SourceExtensions []string `yaml:"source_extensions"`
	ExcludePatterns  []string `yaml:"exclude_patterns"`
}

func Path(repoPath string) string {
	return filepath.Join(repoPath, "docs", "akb", ".config.yaml")
}

func Exists(repoPath string) bool {
	_, err := os.Stat(Path(repoPath))
	return err == nil
}

func Load(repoPath string) (*Config, error) {
	data, err := os.ReadFile(Path(repoPath))
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	if len(cfg.SourceExtensions) == 0 {
		return nil, fmt.Errorf("config has no source_extensions; edit %s or re-run 'akb init'", Path(repoPath))
	}

	return &cfg, nil
}

func Save(repoPath string, cfg *Config) error {
	p := Path(repoPath)
	if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}

	header := []byte("# Generated by akb init. Edit as needed.\n")
	content := append(header, data...)

	if err := os.WriteFile(p, content, 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	return nil
}
